model:
  architecture: yolov8s
  weights: models/weights/pyrosense_fire_v1/weights/best.pt
  fallback_weights: models/weights/fire_smoke_yolov8.pt
  input_size: 640
  device: auto

classes:
  nc: 2
  names:
    0: fire
    1: smoke

inference:
  conf_threshold: 0.35   # Lower than default — fire can be faint
  iou_threshold: 0.45
  max_det: 100
  agnostic_nms: false

# Color coding for visualization
class_colors:
  fire: [255, 69, 0]    # OrangeRed
  smoke: [169, 169, 169] # DarkGray

